# Site settings
title: Michael Dick
email: b.michael.dick@gmail.com
description: "The personal website of Michael Dick."
keywords: "Michael Dick, Product Manager, Seattle"
baseurl: ""
twitter_username: midi2dot0
github_username:  bertique
linkedin_username: in/dickm

# Build settings
markdown: kramdown
permalink: pretty

include:
- .well-known